### PR TITLE
Make the course-progress block dynamic

### LINKED ISSUE #44: Course progress block should be visible to enrolled users only, by default
### 1. Reproduction Steps

+ Create course using the block editor
+ Visit the course page as visitor

### 2. Expected Behavior

+ I would expect to NOT see the course progress bar

### 3. Actual Behavior

+ I can see it

### 4. Error Messages / Logs

n/a

### 5. System Report

LifterLMS: 3.37.16

LifterLMS Blocks: 1.6.0

### 6. Browser, Device, and Operating System

n/a

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description

Fixes #44 

The filters added to not use the id as variable, because I didn't think that having a "dynamic" filter there would have made sense, semantically. 

## How has this been tested?
Manually

## Types of changes
 Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/blocks/class-llms-blocks-pricing-table-block.php [hunk 1]
```diff
@@ -93,9 +103,24 @@ public function output( $attributes = array() ) {
 
 		lifterlms_template_pricing_table( $attributes['post_id'] );
 
+		$block_content = ob_get_clean();
+
+		/**
+		 * Filters the block html.
+		 *
```
Comment (thomasplevy) [inline includes/blocks/class-llms-blocks-pricing-table-block.php:110]:
```suggestion
		 * @since [version]
		 *
```

File: includes/blocks/class-llms-blocks-course-progress-block.php [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+				$this->id,
+				// Take into account the custom class attribute.
+				empty( $attributes['className'] ) ? '' : ' ' . esc_attr( $attributes['className'] ),
+				$progress
+			);
+		}
+
+		/**
+		 * Filters the block html.
+		 *
```
Comment (thomasplevy) [inline includes/blocks/class-llms-blocks-course-progress-block.php:76]:
```suggestion
		 * @since [version]
		 *
```

**Comment by eri-trabiccolo** [comment]
Man I committed your changes requests, but they turned to be 2 cs issues, so I reverted back to the original PR.

Could you please re-check?

**Comment by eri-trabiccolo** [comment]
ahh sorry missing @since ok
