### PR TITLE
Handle '-src' in WordPress version numbers in `LLMS_Blocks::init()`.

### LINKED ISSUE #135: block_categories filter is deprecated
### Reproduction Steps

1. Use the [development version of WordPress 5.8](https://github.com/WordPress/wordpress-develop/tree/5.8.0).
1. Enable WordPress debugging mode in `wp-config.php`.
    ```php
    define( 'WP_DEBUG', true );
    ```
1. Edit any WordPress post or a custom post type like a LifterLMS course.

### Expected Behavior

The WordPress navigation menu is displayed normally without errors or warnings.

### Actual Behavior

The WordPress navigation menu on the left side of the page contains errors.

### Error Messages / Logs

```
Deprecated: block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in C:\WordPress\src\wp-includes\functions.php on line 5458
```

### System and Environment Information

global $wp_version = "5.8-src"

I turned off all WordPress extensions except LifterLMS. When LifterLMS is deactivated, editing a post does not display errors in the WP navigation menu.

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### PR DESCRIPTION
**Pull request by pondermatic**
## Description

Allow `LLMS_Blocks::init()` to handle '-src' in the WordPress version number.

Fixes #135.

## How has this been tested?

Added a unit test with a bunch of version numbers.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/class-llms-blocks.php [hunk 1]
```diff
@@ -169,7 +169,7 @@ public function init() {
 		add_action( 'add_meta_boxes', array( $this, 'remove_metaboxes' ), 999, 2 );
 
 		global $wp_version;
-		$filter = version_compare( $wp_version, '5.8-alpha.1', '>=' ) ? 'block_categories_all' : 'block_categories';
+		$filter = version_compare( $wp_version, '5.8-src', '>=' ) ? 'block_categories_all' : 'block_categories';
```
Comment (thomasplevy) [inline includes/class-llms-blocks.php:174]: function + file versioning & logs please

**Review by thomasplevy — CHANGES_REQUESTED** [review]

File: includes/class-llms-blocks.php (hunk 1 above)
Comment (pondermatic) [reply includes/class-llms-blocks.php:174]: I can't believe I missed that. Thank you.
