### PR TITLE
Fix issue when editing confirmation fields with WordPress 6.0

### LINKED ISSUE #170: Error editing the "Confirm" form blocks.
### Reproduction Steps

1. Use WordPress 6.0. This does not happen with WordPress 5.9.
2. Edit a LifterLMS checkout form.
3. Click on the "Confirm Email Address" block or the "Confirm Password" block.

### Expected Behavior

The block can be edited.
image

### Actual Behavior

The block editor displays "The editor has encountered an unexpected error."

The formatting is different.
image

### Error Messages / Logs

The web browser JavaScript console displays this:
```
Error: Objects are not valid as a React child (found: object with keys {foreground, src}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:13261:17)
    at reconcileChildFibers (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:14163:9)
    at reconcileChildren (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17020:30)
    at mountIndeterminateComponent (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17920:7)
    at beginWork (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:19079:18)
    at HTMLUnknownElement.callCallback (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3942:16)
    at Object.invokeGuardedCallbackDev (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3991:18)
    at invokeGuardedCallback (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:4053:33)
    at beginWork$1 (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:23994:9)
    at performUnitOfWork (https://example.com/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:22806:14)
```
```
react_devtools_backend.js:4026 The above error occurred in the <Icon> component:

    at Icon (https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:19262:5)
    at button
    at Tooltip (https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23958:5)
    at Button (https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:22282:7)
    at fieldset
    at VariationsButtons (https://example.com/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:40639:5)
    at __experimentalBlockVariationTransforms (https://example.com/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:40703:5)
    at div
    at BlockInspectorSingleBlock (https://example.com/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:48408:5)
    at BlockInspector (https://example.com/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:48329:5)
    at div
    at Panel (https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:69076:5)
    at div
    at SlotComponent (https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:22575:5)
    at Slot
    at https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23221:5
    at ComplementaryAreaSlot (https://example.com/wp-includes/js/dist/edit-post.js?ver=0066e2a76eff88129280c12c9a52b6b4:1365:5)
    at div
    at div
    at div
    at div
    at InterfaceSkeleton (https://example.com/wp-includes/js/dist/edit-post.js?ver=0066e2a76eff88129280c12c9a52b6b4:1600:5)
    at Layout (https://example.com/wp-includes/js/dist/edit-post.js?ver=0066e2a76eff88129280c12c9a52b6b4:8669:5)
    at ErrorBoundary (https://example.com/wp-includes/js/dist/editor.js?ver=3f6371e7599e6cefa5d43fae1b61f643:5669:5)
    at BlockRefsProvider (https://example.com/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:9763:5)
    at BlockEditorProvider (https://example.com/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:19413:5)
    at https://example.com/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:19112:7
    at WithRegistryProvider(BlockEditorProvider)
    at BlockContextProvider (https://example.com/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:12871:5)
    at EntityProvider (https://example.com/wp-includes/js/dist/core-data.js?ver=95df951bbac4c9f2fd2e6da80561595d:5570:5)
    at EntityProvider (https://example.com/wp-includes/js/dist/core-data.js?ver=95df951bbac4c9f2fd2e6da80561595d:5570:5)
    at EditorProvider (https://example.com/wp-includes/js/dist/editor.js?ver=3f6371e7599e6cefa5d43fae1b61f643:11575:5)
    at https://example.com/wp-includes/js/dist/editor.js?ver=3f6371e7599e6cefa5d43fae1b61f643:11343:5
    at WithRegistryProvider(EditorProvider)
    at SlotFillProvider (https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23058:5)
    at provider_SlotFillProvider (https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23086:5)
    at Provider (https://example.com/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23235:5)
    at div
    at ShortcutProvider (https://example.com/wp-includes/js/dist/keyboard-shortcuts.js?ver=418fddac042f08102c4110f70e13cd47:763:75)
    at Editor (https://example.com/wp-includes/js/dist/edit-post.js?ver=0066e2a76eff88129280c12c9a52b6b4:8949:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
overrideMethod @ react_devtools_backend.js:4026
logCapturedError @ react-dom.js?ver=17.0.1:20115
callback @ react-dom.js?ver=17.0.1:20184
callCallback @ react-dom.js?ver=17.0.1:12348
commitUpdateQueue @ react-dom.js?ver=17.0.1:12369
commitLifeCycles @ react-dom.js?ver=17.0.1:20739
commitLayoutEffects @ react-dom.js?ver=17.0.1:23456
callCallback @ react-dom.js?ver=17.0.1:3942
invokeGuardedCallbackDev @ react-dom.js?ver=17.0.1:3991
invokeGuardedCallback @ react-dom.js?ver=17.0.1:4053
commitRootImpl @ react-dom.js?ver=17.0.1:23181
unstable_runWithPriority @ react.js?ver=17.0.1:2764
runWithPriority$1 @ react-dom.js?ver=17.0.1:11306
commitRoot @ react-dom.js?ver=17.0.1:23020
performSyncWorkOnRoot @ react-dom.js?ver=17.0.1:22359
(anonymous) @ react-dom.js?ver=17.0.1:11357
unstable_runWithPriority @ react.js?ver=17.0.1:2764
runWithPriority$1 @ react-dom.js?ver=17.0.1:11306
flushSyncCallbackQueueImpl @ react-dom.js?ver=17.0.1:11352
flushSyncCallbackQueue @ react-dom.js?ver=17.0.1:11339
scheduleUpdateOnFiber @ react-dom.js?ver=17.0.1:21923
dispatchAction @ react-dom.js?ver=17.0.1:16169
onStoreChange @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:4076
onChange @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:4084
(anonymous) @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:2872
(anonymous) @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:2330
dispatch @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:863
(anonymous) @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:1647
(anonymous) @ redux-routine.js?ver=5156478c032ea85a2bbdceeb7a43b0c1:854
(anonymous) @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:1541
(anonymous) @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:1635
(anonymous) @ data.js?ver=38ad563aa39c8f314fe6f6e430d81a69:2440
(anonymous) @ block-editor.js?ver=39c7981dd22ec80281080455892940e6:46978
onFocus @ rich-text.js?ver=e7d57502b62ec4756783a0cd79238841:4446
Show 4 more frames
```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://example.com
Site Url: https://example.com
Login Url: https://example.com/wp-login.php
Version: 6.0.1-alpha-53446
Debug Mode: Yes
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /archives/%post_id%
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.5.0
Db Version: 6.5.0
Course Catalog: Course Catalog (#561) [https://example.com/courses]
Membership Catalog: Membership Catalog (#562) [https://example.com/memberships]
Student Dashboard: Dashboard (#564) [https://example.com/dashboard]
Checkout Page: Purchase (#563) [https://example.com/purchase]
Course Catalog Per Page: 6
Course Catalog Sorting: title,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: medium
Terms Required: yes
Terms Page: Sample Page (#2) [https://example.com/sample-page]
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: required
Registration Email Confirmation: no
Account Names: required
Account Address: hidden
Account Phone: hidden
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: james@happycorner.us
Email From Name: Happy Corner
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 10.2.9
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 202 MB
Php Memory Limit: 328M
Php Post Max Size: 208M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 600
Php Version: 8.0.17
Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0h mod_fcgid/2.3.9
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty-Two
Version: 1.2
Themeuri: https://wordpress.org/themes/twentytwentytwo/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.5.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [X] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

Brave V1.39.111 (May 24, 2022)
Windows 10

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description

Fixes #170 
Also fixes columns box-sizing in the editor (as reported by the same user on slack)

## How has this been tested?
manually:
- with WP 5.9 with and without the Gutenberg plugin (version 13+)
- with WP 6.0 with and without the Gutenberg plugin (version 13+)

## Types of changes

Bug fix (non-breaking change which fixes an issue) 

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/class-llms-blocks-assets.php [hunk 1]
```diff
@@ -184,6 +193,19 @@ private function use_bc_assets() {
...
 
+	/**
+	 * Can a variation transform icon be an object.
+	 *
+	 * @since [version]
+	 *
+	 * @return boolean
+	 */
+	private static function can_variation_transform_icon_be_an_object() {
+		// https://github.com/gocodebox/lifterlms-blocks/issues/170.
```
Comment (thomasplevy) [inline includes/class-llms-blocks-assets.php]:
```suggestion
	/**
	 * Can a variation transform icon be an object.
	 *
	 * @since [version]
	 *
	 * @link https://github.com/gocodebox/lifterlms-blocks/issues/170
	 *
	 * @return boolean
	 */
	private static function can_variation_transform_icon_be_an_object() {
```

**Comment by thomasplevy** [comment]
@eri-trabiccolo are e2e tests failing because of this bug (and need to be updated) or are the failures unrelated? I haven't been keeping my eye on them too closely as I've been heads down on PayPal and checkout changes in the core... Have you looked?

File: .changelogs/issue_170-1.yml [hunk 2]
```diff
@@ -0,0 +1,6 @@
+significance: patch
+type: fixed
+links:
+  - "#170"
+entry: Fixed an issue that prevented to edit confirmation fields when running
+  WordPress 6.0.
```
Comment (thomasplevy) [inline .changelogs/issue_170-1.yml]:
```suggestion
entry: Fixed an issue that prevented editing form confirmation fields when running
  WordPress 6.0.
```

File: .changelogs/issue_170.yml [hunk 3]
```diff
@@ -0,0 +1,3 @@
+significance: patch
+type: fixed
+entry: Fix field columns sizing in the block editor.
```
Comment (thomasplevy) [inline .changelogs/issue_170.yml]:
```suggestion
entry: Fixed field columns sizing in the block editor.
```

**Review by thomasplevy — CHANGES_REQUESTED** [review]

**Comment by eri-trabiccolo** [comment]
@thomasplevy I'm working on the failing tests.
