### PR TITLE
Issue/41

### LINKED ISSUE #41: Block visibility settings do not apply to Classic (editor) block
### 1. Reproduction Steps

+ Create a course with a Classic (editor) block
+ set the Classic block Enrollment Visibility to 'logged in users'
+ save
+ visit the course as logged out user (or refresh the editor page)

### 2. Expected Behavior

+ I'd expect to not see the classic block content not displayed
(after refreshing the editor page if you check that setting you can see your change has been not saved)

### 3. Actual Behavior

+ classic block content was displayed

### 4. Error Messages / Logs

n/a

### 5. System Report

n/a

### 6. Browser, Device, and Operating System

n/a

### Considerations
If I look at the course content with the code editor I can see that the classic block doesn't look like the other blocks, it's not wrapped into something like:
```
<!-- wp:classic {"llms_visibility_in":"this"} -->
<p>classic content</p>
<!-- /wp:classic -->
```
(or something of the sort)
as I would expected, but it's just:
```
<p>classic content</p>
```
so, of course, there's no place where to save the visibility attribute. I guess we should just disable the Block visibility settings for the classic block.

### PR DESCRIPTION
**Pull request by thomasplevy**
Adds a "blacklist" check when determining if block visibility attributes are supported by the block.

Fixes #41

### CODE REVIEW

File: assets/src/block-visibility/check.js [hunk 1]
```diff
@@ -22,8 +23,30 @@ export default function supportsVisibility( settings, name ) {
...
+ * Returns a list of blocks that we've decided should not support block visibility
+ *
+ * @since [version]
+ *
+ * @return {Array} List of block names.
+ */
+const getBlacklist = () => {
+	return [
+		/**
+		 * Otherwise know as the "Classic" block
```
Comment (eri-trabiccolo) [inline assets/src/block-visibility/check.js:46]:
```suggestion
		 * Otherwise known as the "Classic" block.
```

File: assets/src/block-visibility/attributes.js [hunk 2]
```diff
@@ -23,6 +23,7 @@ import check from './check';
 export default function visibilityAttributes( settings, name ) {
 
 	if ( ! check( settings, name ) ) {
+		console.log( name );
```
Comment (eri-trabiccolo) [inline assets/src/block-visibility/attributes.js:26]:
```suggestion
```
